name: Run Python Scripts

on:
  workflow_run:
    workflows: ["Run Python Scripts and Commit CSV Files"]
    types:
      - completed

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Update pip
        run: |
          python -m pip install --upgrade pip

      - name: Install requirements
        run: |
          python -m pip install requests_html numpy pandas yfinance  # Install necessary dependencies

      - name: Run name-change.py script
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Running name-change.py script..."
          python name-change.py  # Run the name-change.py script

      - name: Commit CSV files
        run: |
          echo "Checking for changes in CSV files..."
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add *.csv  # Add any changed CSV files
          git commit -m "Auto-commit CSV files" || true  # Continue even if no changes to commit
          git push || true  # Continue even if there’s nothing to push
