name: Run Python Scripts and Commit CSV Files

on:
  workflow_dispatch:  # Triggered manually
  schedule:
    - cron: '0 0 * * *'  # Run every 24 hours at midnight

jobs:
  build:
    name: MF Holdings
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Check for CSV Files
        run: |
          echo "Checking for CSV files..."
          if [ -n "$(find . -maxdepth 1 -name '*.csv' -print -quit)" ]; then
            echo "CSV files found. Deleting..."
            find . -type f -name "*.csv" -delete
          else
            echo "No CSV files found. Skipping deletion."
            exit 0  # Exit successfully to skip the next steps
          fi
        id: check-csv  # Added step id for conditional logic

      - name: Commit and Push Changes
        if: steps.check-csv.outcome == 'success'  # Only run this step if CSV files were found and deleted
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Delete CSV files" || true  # Continue if there are no changes
          git push

      - name: Install dependencies in virtual environment
        run: |
          python -m venv venv  # Create virtual environment
          source venv/bin/activate  # Activate virtual environment
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace 'requirements.txt' with the actual path

      - name: Run Python Scripts
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          source venv/bin/activate  # Activate virtual environment
          python MFCode.py
          python Benchmark.py
          python "Historical Returns.py"
          python "Index Latest.py"
          python "Peer Comparison.py"
          python "Scheme Risk.py"
          python "Returns Data.py"
          
      - name: Commit CSV files
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add *.csv  # Replace 'path/to/your/csv/files' with the actual path
          git commit -
