name: Run JavaScript Script

on:
  workflow_dispatch:  # Triggered manually

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        
      - name: Install dependencies
        run: npm install axios

      - name: Run JavaScript script with jQuery
        run: node MF_Holdings.js

      - name: Run Output.js
        run: node Output.js

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output.csv
          git commit -m "Update output.csv"
          git push
