name: Run Python Scripts and Commit CSV Files

on:
  workflow_dispatch:  # Triggered manually
  schedule:
    - cron: '0 0,12 * * *'  # Run every 12 hours

jobs:
  build:
    name: MF Holdings
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt  # Replace 'path/to/requirements.txt' with the actual path

      - name: Run Python Scripts
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          python MFCode.py
          python BSEData.py
          python Stkcode.py
          python Holdings.py

      - name: Commit CSV files
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add *.csv
          git commit -m "Auto-commit CSV files"
          git push
