name: Trigger Workflow

on:
  workflow_run:
    workflows: ["Run Python Scripts and Commit CSV Files"]
    types:
      - completed

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Repository B
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          event-type: custom-event
          
